
# simulation clock
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msg.Clock"
  direction: GZ_TO_ROS

# joint states
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/empty/model/amber_b1_full_robot/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# tf
- ros_topic_name: "/tf"
  gz_topic_name: "/model/amber_b1_full_robot/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# arm_joint_trajectory
- ros_topic_name: "/arm_joint_trajectory"
  gz_topic_name: "/model/amber_b1_full_robot/joint_trajectory"
  ros_type_name: "trajectory_msgs/msg/JointTrajectory"
  gz_type_name: "gz.msgs.JointTrajectory"
  direction: ROS_TO_GZ

